---
name: build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ['go']
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout
        uses: actions/checkout@v2

      - name: Format
        run: go fmt dbyml/*.go

      - name: Install golangci
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.48.0

      # - name: Golangci-lint
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     version: v1.29
      #     skip-cache: false
      #     skip-pkg-cache: false
      #     skip-build-cache: false

      - name: Golangci-lint
        run: golangci-lint run dbyml -v

      - name: Build
        run:
          go build .
